### ISSUE TITLE
Make buildable from Bazel

### ISSUE THREAD

**Issue by acmcarther** [acmcarther/cargo-raze#14]
Now that I've figured out how to make openssl compile (gory details in my demo repo: https://github.com/acmcarther/compile_openssl), we should be able to produce a WORKSPACE file, and run cargo-raze on this project.

That would allow us to promote the running of cargo-raze into a Bazel build rule, which would eliminate the need to run it manually.

This actually also unlocks running cargo-raze for cargo-vendor as well, which would facilitate performing vendoring in a Bazel build rule as well -- ultimately narrowing down the process of using cargo raze to just including a toml.

**Comment by mfarrugi** [comment]
How do you envision vendoring from a build rule? I think the general
vendoring workflow assumes `bazel build` is run offline.

**Comment by acmcarther** [comment]
Well, there is an initial roadblock... Vendoring ought to happen as a WORKSPACE rule, but it can't if it relies on locally compiled code (which has to happen in a normal build rule -- after WORKSPACE rules are evaluated). It sort of ends up as a chicken-or-egg problem, and the benefit isn't very significant. Since all configuration happens in the Cargo.toml, its not hard at this point to just write a genrule to perform the re-vendoring and `cargo-raze`-ing.

Needs more thought.

**Comment by acmcarther** [comment]
I don't think I'm interested in this feature at this point. I believe any serious user would likely not be interested in making changing the external dependencies _too_ easy, as there exists a risk of breakages in the monorepo.

In addition, https://github.com/acmcarther/cargo-raze/issues/22 prescribes a process that eliminates the vendoring, which reduces the procedure down to only running cargo-raze and committing the changes.
