### ISSUE TITLE
Using //third_party results in lots of errors

### ISSUE THREAD

**Issue by SirVer** [acmcarther/cargo-raze#28]
Bazel actually enforces a license for BUILD files in //third_party.

~~~
ERROR: /Users/hrapp/Desktop/Programming/rust/point_cloud_viewer/third_party/rust/vendor/cfg-if-0.1.2/BUILD:16:1: third-party rule '//third_party/rust/vendor/cfg-if-0.1.2:cfg_if' lacks a license declaration with one of the following types: notice, reciprocal, permissive, restricted, unencumbered, by_exception_only
~~~

**Comment by acmcarther** [comment]
We should use the license information thats already available in the toml to generate a license clause in generated BUILD files.

Template: https://github.com/acmcarther/cargo-raze/blob/master/src/templates/remote_crate.BUILD.template
Toml struct (add a license field): https://github.com/acmcarther/cargo-raze/blob/master/src/settings.rs#L22
Propagate to Context object so its available in template: https://github.com/acmcarther/cargo-raze/blob/master/src/context.rs#L21
Via planning code: https://github.com/acmcarther/cargo-raze/blob/master/src/planning.rs#L63

Will look into this ASAP

**Comment by acmcarther** [comment]
to be clear "we should" in this context means "a change needs to be made", not "this  should already be working"

**Comment by SirVer** [comment]
This will require a lookup table build on the info from here: https://opensource.google.com/docs/thirdparty/licenses/.

A typical output in a `//third_party` build file is 

~~~
# MIT
license("notice")
~~~~

I think the comment would be from the Cargo.toml field.
