### ISSUE TITLE
Support for targeting multiple architectures

### ISSUE THREAD

**Issue by negator** [acmcarther/cargo-raze#33]
It would be great if there was a straightforward way to add support for multiple architectures at once. A bit like how the Bazel `--ios_multi_cpus` works, but perhaps just allow an array of `targets` in `Cargo.toml`, which generates arch specific rules.

**Comment by acmcarther** [comment]
Can you reopen this in google/cargo-raze?

Response to both:

---

I'm certainly open to this, but each target generates features, build scripts, and dependencies that are different, and I haven't had a chance to give enough though to the best way to organize the generated files. Do you have any ideas in that respect?

EDIT: I'll look into how `ios_multi_cpus` works.
